baseurl: ''
exclude: ['README.md', 'stackbit.yaml', 'LICENSE', 'netlify.toml']
permalink: pretty
title: 'Journalism by Zachary Klosko'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: '<a class="zerostatic" href="https://www.github.com/zklosko/zklosko.github.io">Content</a> by Zachary Klosko. Theme by <a class="zerostatic" href="https://www.zerostatic.io">Zerostatic</a>.'

seo:
  meta_og_title: "Journalism by Zachary Klosko"
  meta_og_type: "website"
  meta_og_url: "https://zklosko.github.io"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Every story has two sides; it's my goal to make both sides easily readable, watchable, and transmittable."
  meta_twitter_card: "summary"
  meta_twitter_site: "@zklosko"
  meta_twitter_creator: "@zklosko"


excerpt_separator: <!--more-->

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
